# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Orange Blog
tagline:             '橘子的Blog'
description:         '隨便寫寫～'
url:                 https://star32134212.github.io/OrangeBlog/
baseurl:             '/OrangeBlog'
paginate:            5

# About/contact
author:
  name:              Orange
  github:            https://github.com/star32134212
  email:             star32134212@gmail.com

# Handling reading
encoding: "utf-8"

# Custom vars
version:             1.0.0

# Social links
github_username:      star32134212
instagram_username:   orangekutar
twitter_username:     star32134212
facebook_username:    姜林寬

# Tag: generate pages for each tag where we can list posts
collections:
  tag:
    output: true

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: OrangeBlog
